# Generated by Django 5.1.2 on 2025-01-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('bestlink', models.CharField(max_length=200)),
                ('weekgetlinks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('flight_num', models.CharField(max_length=10)),
                ('eprice', models.IntegerField(null=True)),
                ('dept_time', models.TimeField()),
                ('dest_time', models.TimeField()),
                ('company', models.CharField(default=' ', max_length=15)),
                ('seats', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=500)),
                ('hotel_price', models.IntegerField(null=True)),
                ('hotel_rating', models.IntegerField(null=True)),
                ('amenities', models.CharField(max_length=500)),
                ('distfromap', models.IntegerField(null=True)),
                ('rooms', models.IntegerField(default=0)),
                ('image1', models.ImageField(null=True, upload_to='img/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.city')),
            ],
        ),
    ]
