# Generated by Django 5.1.2 on 2025-01-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_remove_provider_user_tourpackage_tourprovideruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_package_images/'),
        ),
    ]
