# Generated by Django 5.1.2 on 2025-02-07 17:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
